### ISSUE TITLE
Question on scope + P3

### ISSUE THREAD

**Issue by palemieux** [WICG/canvas-color-space#15]
> Canvases should be able to take advantage of the full color gamut and dynamic range of the display device.

There are literally thousands of different display device characteristics, and more coming, so I do not recommend setting this as a goal.

I would instead focus on color systems routinely used for interchange, namely:

- sRGB
- ITU Rec. 709 (minor differences from sRGB)
- ITU Rec 2020 (Wide Gamut content)
- ITU Rec 2100 (for HDR and Wide Gamut content) [same color primaries and white point as ITU Rec 2020]

> The "p3" color space

There is no such thing as a P3 color space (see https://lists.w3.org/Archives/Public/www-style/2016Sep/0092.html)

More importantly perhaps, the P3 color gamut essentially fits within the ITU Rec 2020/2100 gamut.

**Comment by dwsinger** [comment]
I think that there are P3 color primaries. 'Color space' is an ambiguous term (do you mean RGB vs. YCbCr vs. ICtCp vs., or sRGB vs P3 vs. 2100 color primaries? The term is used for both)

**Comment by jdashg** [comment]
"display-p3" is what we mean by "p3", and I think a recent PR fixed this.
Display P3 is P3 primaries, with sRGB whitepoint (D65) and transfer function.

**Comment by svgeesus** [comment]
> I think that there are P3 color primaries. 'Color space' is an ambiguous term

No, color space is clearly defined and, for a relative-luminance and additive system, a colorspace is defined by:

1. the color primaries
2. the media white, which is also assumed to be the primary adaptive stimulus
3. the transfer curve or EOTF
4. the image state and viewing conditions

Display-P3 is defined by:

1. The color primaries of Digital Cinema Initiative (DCI) P3 colorspace
2. the media white, EOTF, image state and viewing conditions of sRGB

In practice, display-p3 has taken over from the older Adobe 1998 RGB space as a WCG display target and most streaming TV and movie content is mastered to a gamut bounded by the P3 primaries (but transmitted in a BT.2020 container, thus requiring slightly greater bit depth to avoid banding, largely because ITU H.273 and HDMI do not support any P3 colorspace).

**Comment by dwsinger** [comment]
I fear that "color space" can easily be ambiguous, as I hear it mean at least these three, which are not the same:
* the triangle inside the declared color primaries (literally, the space of possible colors)
* the transformation of RGB into a different number space (YUV, YCrCb, HLS, etc.), the matrix,
* some combination of definitions, like the combination Chris uses.

Which generally had led me to try to avoid it as a term; speak about the primaries, or the matrix, etc.

**Comment by brianosman** [comment]
> * the transformation of RGB into a different number space (YUV, YCrCb, HLS, etc.)

Yes. Although I (and Skia) use 'color space' to mean a combination of primaries and transfer functions, this alternate definition is very common in other publications, libraries, etc. Essentially: A set of axes used to describe colors (note that several of these are not a linear transformation of XYZ), and in applications that use this definition, it's often not a *specific* definition of the axis values, just a categorical one about what the axes "are".

**Comment by Headcrabed** [comment]
> "display-p3" is what we mean by "p3", and I think a recent PR fixed this. Display P3 is P3 primaries, with sRGB whitepoint (D65) and transfer function.

@kdashg sRGB has a special behavior that though it’s using piecewise transfer function in most cases, the reference display would use power 2.2 transfer function rather than the piecewise one. Does Display P3 have the same behavior?
