### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/canvas-color-space#26]
Hi, just wondering if this repository is still active and/or if this made it into the HTML spec? If work on this has stopped, can we archive this incubation?

**Comment by svgeesus** [comment]
I'm hoping it is still open!

The [issue on html](https://github.com/whatwg/html/issues/4167) seems to have stalled, apparently because of [unaddressed review comments on a PR](https://github.com/whatwg/html/pull/3882) and [waiting for implementations on a PR](https://github.com/whatwg/html/pull/3926)

**Comment by marcoscaceres** [comment]
Ok, cool. Thanks for the update... "carry on", as they say :)
